### ISSUE TITLE
API Docs have wrong properties for platform type / enum

### ISSUE THREAD

**Issue by pavog** [HangarMC/Hangar#1269]
### Observed/problematic behavior

The automatically generated openapi specification file for Hangars API contains an error for the Platform type.
It is defined the following way:
```yaml
    Platform:
      maxLength: 3
      minLength: 1
      type: string
      description: Server platform
      example: PAPER
      enum:
      - PAPER
      - WATERFALL
      - VELOCITY
```
The problem here are: `maxLength` and `minLength`.
These two properties simply do not belong here.
It also makes it impossible to use the download endpoint (/api/v1/projects/{slug}/versions/{name}/{platform}/download) using the ui for the api-docs (https://hangar.papermc.io/api-docs#/Versions/downloadVersion).

See the attached screenshot:
![image](https://github.com/HangarMC/Hangar/assets/4786628/01bc3625-b35c-4707-8e71-0f96b019aacd)

### Expected behavior

I should be able to choose all 3 platforms (PAPER, WATERFALL or VELOCITY) on the UI and don't get an error.
The properties `maxLength` and `minLength` for `Platform` should not be in the generated open api specification file.

### Steps to reproduce

1. Go to https://hangar.papermc.io/api-docs#/Versions/downloadVersion
2. Click "Try it out"
3. Enter a project slug. Example: ViaVersion
4. Enter a version name. Example: 4.8.0-1.20.2-pre1-SNAPSHOT+14
5. Choose a platform. Example: PAPER
6. Click "Execute"
